export const ENABLE_AGENT_CLI_TOOLS = true
export const ENABLE_AGENT_CONTENT_MODERATION = true
export const ENABLE_AGENT_KNOWLEDGE_RETRIEVAL = true
export const ENABLE_AGENT_SECRET_ENV_VARIABLES = true
